import Head from "next/head";
import Image from "next/image";
import { colors, currentTheme } from "~/colors";
import { dmSans, robotoMono } from "~/font";
import Button from "~/components/Button";
import LeftDashText from "~/components/LeftDashText";
import HomeServicesCard from "~/components/HomeServicesCard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex items-center justify-between bg-gradient-to-r from-[#ECECEE] to-[#ECE7EB] px-14 py-28 max-md:flex-col">
          <div className="flex w-[50%] flex-col gap-8">
            <p
              className={`${robotoMono.className} text-8xl  uppercase text-[${currentTheme.lightText}]`}
            >
              One-stop auto service solution.
            </p>
            <p className={`text-[${currentTheme.deepText}]`}>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam
              provident placeat doloremque id laborum aliquid.
            </p>
            <div className="flex justify-between">
              <Button
                hasGradient={true}
                hasShadow={true}
                text="REQUEST APPOINTMENT"
              />
              <Button
                hasGradient={false}
                hasShadow={false}
                bgColor={colors.dark}
                text="GET AN ESTIMATE"
              />
            </div>
          </div>
          <div className="ml-auto">
            <Image
              src="/image/engine.webp"
              alt="engine"
              width="450"
              height="463"
            ></Image>
          </div>
        </div>

        <div className="flex flex-col gap-8 px-14 pb-28 pt-20">
          <div className="flex flex-col items-center justify-center gap-5">
            <LeftDashText text="Our Services" />
            <span className={`text-5xl  font-semibold ${dmSans.className}`}>
              Your One-Stop Auto Repairs Solutions
            </span>
          </div>
          <div className="grid grid-cols-3 gap-x-3 gap-y-12">
            <HomeServicesCard
              category="Repairs"
              details="
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto quos recusandae earum itaque quis iste quibusdam amet magni nobis labore."
              imgSrc="/image/belt.webp"
              title="Belt & Hoses"
            />
            <HomeServicesCard
              category="Servicing"
              details="
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto quos recusandae earum itaque quis iste quibusdam amet magni nobis labore."
              imgSrc="/image/battery.webp"
              title="Car Batteries & Charging"
            />
            <HomeServicesCard
              category="Repairs"
              details="
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto quos recusandae earum itaque quis iste quibusdam amet magni nobis labore."
              imgSrc="/image/mechanical.webp"
              title="Mechanical Repairs"
            />
            <HomeServicesCard
              category="Servicing"
              details="
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto quos recusandae earum itaque quis iste quibusdam amet magni nobis labore."
              imgSrc="/image/painting.jpeg"
              title="Bodywork & Paint"
            />
            <HomeServicesCard
              category="Repairs"
              details="
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto quos recusandae earum itaque quis iste quibusdam amet magni nobis labore."
              imgSrc="/image/radiator.webp"
              title="Radiator & Engine Cooling"
            />
          </div>
        </div>
      </main>
    </>
  );
}
