import '~/styles/globals.css';

// import { Inter } from "next/font/google";
import MainMenu from '~/components/MainMenu';
import MobileMenu from '~/components/MobileMenu';
import { manRope } from '~/font';
import Footer from '~/components/Footer';

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-sans",
// });

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // className={`font-sans ${inter.variable}`}
  return (
    <html lang="en" className={manRope.className}>
      <body className={manRope.className}>
        <MainMenu />
        <MobileMenu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
