import '~/styles/globals.css';

// import { Inter } from "next/font/google";
import MainMenu from '~/components/MainMenu';
import MobileMenu from '~/components/MobileMenu';
import { manRope } from '~/font';
import Footer from '~/components/Footer';
import { Session, getSession } from '@auth0/nextjs-auth0';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import User from './api/user/logic';
import Auth0 from '~/server/auth0';

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-sans",
// });

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const auth0Class = new Auth0();
  // const auth0User = await auth0Class.findOrCreateAuth0User();
  // className={`font-sans ${inter.variable}`}

  return (
    <html lang="en" className={manRope.className}>
      <UserProvider>
        <body className={manRope.className}>
          <MainMenu />
          <MobileMenu />
          {children}
          <Footer />
        </body>
      </UserProvider>
    </html>
  );
}
